apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- accounting-service.yaml

configMapGenerator:
- envs:
  - .env
  name: cm-accounting-service
generatorOptions:
  disableNameSuffixHash: true

images:
- name: ghcr.io/azure/reddog-demo/reddog-java-accounting-service
  newName: crreddogs.azurecr.io/reddog/accounting-service
  newTag: latest
